In [19]:
import numpy as np

import pandas as pd

from pandas import DataFrame, Series

In [20]:
import webbrowser
website = 'https://en.wikipedia.org/wiki/List_of_all-time_NFL_win%E2%80%93loss_records'

In [21]:
webbrowser.open(website)

True

In [22]:
nfl_frame = pd.read_clipboard()

In [23]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,914,520,388,6,0.572,1960,NFC East
1,2,Green Bay Packers,"1,368",756,574,38,0.567,1921,NFC North
2,3,New England Patriots,916,512,395,9,0.564,1960,AFC East
3,4,Chicago Bears,"1,402",769,591,42,0.563,1920,NFC North
4,5,Baltimore Ravens,384,214,169,1,0.559,1996,AFC North
5,6,Miami Dolphins,832,457,371,4,0.552,1966,AFC East
6,7,Minnesota Vikings,902,488,403,11,0.547,1961,NFC North
7,8,San Francisco 49ers,"1,034",545,475,14,0.534,1950,NFC West
8,9,New York Giants,"1,337",696,608,33,0.533,1925,NFC East
9,10,Denver Broncos,916,483,423,10,0.533,1960,AFC West

In [24]:
nfl_frame.tail()

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
5,6,Miami Dolphins,832,457,371,4,0.552,1966,AFC East
6,7,Minnesota Vikings,902,488,403,11,0.547,1961,NFC North
7,8,San Francisco 49ers,"1,034",545,475,14,0.534,1950,NFC West
8,9,New York Giants,"1,337",696,608,33,0.533,1925,NFC East
9,10,Denver Broncos,916,483,423,10,0.533,1960,AFC West

In [33]:
nfl_frame.ix[2]

C:\Users\Apoorv\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

Rank                                   3
Team                New England Patriots
GP                                   916
Won                                  512
Lost                                 395
Tied                                   9
Pct.                               0.564
First NFL Season                    1960
Division                        AFC East
Name: 2, dtype: object

In [41]:
nfl_frame['Stadium '] = ('AT&T')

In [43]:
del nfl_frame['Stadium ']

In [44]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,914,520,388,6,0.572,1960,NFC East
1,2,Green Bay Packers,"1,368",756,574,38,0.567,1921,NFC North
2,3,New England Patriots,916,512,395,9,0.564,1960,AFC East
3,4,Chicago Bears,"1,402",769,591,42,0.563,1920,NFC North
4,5,Baltimore Ravens,384,214,169,1,0.559,1996,AFC North
5,6,Miami Dolphins,832,457,371,4,0.552,1966,AFC East
6,7,Minnesota Vikings,902,488,403,11,0.547,1961,NFC North
7,8,San Francisco 49ers,"1,034",545,475,14,0.534,1950,NFC West
8,9,New York Giants,"1,337",696,608,33,0.533,1925,NFC East
9,10,Denver Broncos,916,483,423,10,0.533,1960,AFC West

In [45]:
data= { 'city' : ['Agra', 'Delhi', 'Pune'] , 'Population': [4380793, 16753235, 3124458]}